storage:
  type: clickhouse
  connectionString: tcp://signoz-clickhouse:9000/?database=signoz_traces

database: signoz_traces
host: signoz-clickhouse
port: 9000
username: default
password: ""

metrics:
  pollFrequency: 10s
  maxQueryLength: 5000
  queryTimeout: "30s"
  maxDataPoints: 1440

logging:
  level: info

traces:
  maxDuration: "24h"
  maxSpans: 1000000
  maxAttributes: 100
  maxAttributeLength: 1000
  maxAnnotations: 100
  maxAnnotationLength: 1000

features:
  liveView: true
  serviceHealth: true
  usageExplorer: true
  logs: true
  experimentalFeatures: true
  enableHistograms: true
  enableSpanMetrics: true
  enableServiceGraph: true
  enableNewSpanSchema: true
  enableNewMetricsSchema: true
  enableNewLogsSchema: true
