apiVersion: v1
kind: ConfigMap
metadata:
  name: medapp-common-config
  namespace: medapp-services
data:
  CONSUL_HOST: "consul.medapp-infra.svc.cluster.local"
  CONSUL_PORT: "8500"
  MONGODB_URI: "mongodb://mongodb.medapp-infra.svc.cluster.local:27017"
  REDIS_HOST: "redis.medapp-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq.medapp-infra.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.medapp-monitoring.svc.cluster.local:4317"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  LOG_FORMAT: "json"
  LOG_LEVEL: "DEBUG"
  AUTH_SERVICE_URL: "http://auth-service.medapp-services.svc.cluster.local:8086"
  KEYCLOAK_URL: "http://keycloak.medapp-infra.svc.cluster.local:8080/auth"
  KEYCLOAK_REALM: "medapp"
  KEYCLOAK_CLIENT_ID: "medapp-api"
