global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "medecins-service"
    static_configs:
      - targets: ["medecins-service:8081"]

  - job_name: "ordonnances-service"
    static_configs:
      - targets: ["ordonnances-service:8082"]

  - job_name: "patients-service"
    static_configs:
      - targets: ["patients-service:8083"]

  - job_name: "radiologues-service"
    static_configs:
      - targets: ["radiologues-service:8084"]

  - job_name: "reports-service"
    static_configs:
      - targets: ["reports-service:8085"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
