global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "medecins-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["medecins-service:9091"]

  - job_name: "ordonnances-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["ordonnances-service:9092"]

  - job_name: "patients-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["patients-service:9093"]

  - job_name: "radiologues-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["radiologues-service:9094"]

  - job_name: "reports-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["reports-service:9095"]

  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

