apiVersion: v1
kind: Namespace
metadata:
  name: medapp-infra
  labels:
    name: medapp-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: medapp-services
  labels:
    name: medapp-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: medapp-monitoring
  labels:
    name: medapp-monitoring
