server_endpoint: ws://signoz:4320/v1/opamp

receivers:
  smartagent/signalfx:
    endpoint: ${env:SIGNALFX_ENDPOINT}/v2/datums
    access_token: ${env:SIGNALFX_TOKEN}
    sync_host_metadata: false

exporters:
  logging:
    loglevel: debug
  otlp/signoz:
    endpoint: signoz:4317
    tls:
      insecure: true
    timeout: 30s
  otlphttp/signoz:
    endpoint: signoz:4318
    timeout: 30s
    tls:
      insecure: true

service:
  pipelines:
    metrics/smartagent:
      receivers:
        - smartagent/signalfx
      exporters:
        - otlp/signoz
        - logging
